/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedReportsRouteImport } from './routes/saved-reports'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as CriteriaRouteImport } from './routes/criteria'
import { Route as IndexRouteImport } from './routes/index'

const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedReportsRoute = SavedReportsRouteImport.update({
  id: '/saved-reports',
  path: '/saved-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriaRoute = CriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criteria': typeof CriteriaRoute
  '/forecasting': typeof ForecastingRoute
  '/grades': typeof GradesRoute
  '/reports': typeof ReportsRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
  '/teacher': typeof TeacherRoute
  '/timetable': typeof TimetableRoute
  '/utilities': typeof UtilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criteria': typeof CriteriaRoute
  '/forecasting': typeof ForecastingRoute
  '/grades': typeof GradesRoute
  '/reports': typeof ReportsRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
  '/teacher': typeof TeacherRoute
  '/timetable': typeof TimetableRoute
  '/utilities': typeof UtilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criteria': typeof CriteriaRoute
  '/forecasting': typeof ForecastingRoute
  '/grades': typeof GradesRoute
  '/reports': typeof ReportsRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
  '/teacher': typeof TeacherRoute
  '/timetable': typeof TimetableRoute
  '/utilities': typeof UtilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criteria'
    | '/forecasting'
    | '/grades'
    | '/reports'
    | '/saved-reports'
    | '/settings'
    | '/teacher'
    | '/timetable'
    | '/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criteria'
    | '/forecasting'
    | '/grades'
    | '/reports'
    | '/saved-reports'
    | '/settings'
    | '/teacher'
    | '/timetable'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/criteria'
    | '/forecasting'
    | '/grades'
    | '/reports'
    | '/saved-reports'
    | '/settings'
    | '/teacher'
    | '/timetable'
    | '/utilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriteriaRoute: typeof CriteriaRoute
  ForecastingRoute: typeof ForecastingRoute
  GradesRoute: typeof GradesRoute
  ReportsRoute: typeof ReportsRoute
  SavedReportsRoute: typeof SavedReportsRoute
  SettingsRoute: typeof SettingsRoute
  TeacherRoute: typeof TeacherRoute
  TimetableRoute: typeof TimetableRoute
  UtilitiesRoute: typeof UtilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-reports': {
      id: '/saved-reports'
      path: '/saved-reports'
      fullPath: '/saved-reports'
      preLoaderRoute: typeof SavedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criteria': {
      id: '/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof CriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriteriaRoute: CriteriaRoute,
  ForecastingRoute: ForecastingRoute,
  GradesRoute: GradesRoute,
  ReportsRoute: ReportsRoute,
  SavedReportsRoute: SavedReportsRoute,
  SettingsRoute: SettingsRoute,
  TeacherRoute: TeacherRoute,
  TimetableRoute: TimetableRoute,
  UtilitiesRoute: UtilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
