/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SyndicateRouteImport } from './routes/syndicate'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedReportsRouteImport } from './routes/saved-reports'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as CriteriaRouteImport } from './routes/criteria'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AiAnalyserRouteImport } from './routes/ai-analyser'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as IndexRouteImport } from './routes/index'

const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateRoute = SyndicateRouteImport.update({
  id: '/syndicate',
  path: '/syndicate',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedReportsRoute = SavedReportsRouteImport.update({
  id: '/saved-reports',
  path: '/saved-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriaRoute = CriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyserRoute = AiAnalyserRouteImport.update({
  id: '/ai-analyser',
  path: '/ai-analyser',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/ai-analyser': typeof AiAnalyserRoute
  '/changelog': typeof ChangelogRoute
  '/criteria': typeof CriteriaRoute
  '/forecasting': typeof ForecastingRoute
  '/grades': typeof GradesRoute
  '/inbox': typeof InboxRoute
  '/notebook': typeof NotebookRoute
  '/peers': typeof PeersRoute
  '/reports': typeof ReportsRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/syndicate': typeof SyndicateRoute
  '/teacher': typeof TeacherRoute
  '/timetable': typeof TimetableRoute
  '/utilities': typeof UtilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/ai-analyser': typeof AiAnalyserRoute
  '/changelog': typeof ChangelogRoute
  '/criteria': typeof CriteriaRoute
  '/forecasting': typeof ForecastingRoute
  '/grades': typeof GradesRoute
  '/inbox': typeof InboxRoute
  '/notebook': typeof NotebookRoute
  '/peers': typeof PeersRoute
  '/reports': typeof ReportsRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/syndicate': typeof SyndicateRoute
  '/teacher': typeof TeacherRoute
  '/timetable': typeof TimetableRoute
  '/utilities': typeof UtilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/ai-analyser': typeof AiAnalyserRoute
  '/changelog': typeof ChangelogRoute
  '/criteria': typeof CriteriaRoute
  '/forecasting': typeof ForecastingRoute
  '/grades': typeof GradesRoute
  '/inbox': typeof InboxRoute
  '/notebook': typeof NotebookRoute
  '/peers': typeof PeersRoute
  '/reports': typeof ReportsRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/syndicate': typeof SyndicateRoute
  '/teacher': typeof TeacherRoute
  '/timetable': typeof TimetableRoute
  '/utilities': typeof UtilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced'
    | '/ai-analyser'
    | '/changelog'
    | '/criteria'
    | '/forecasting'
    | '/grades'
    | '/inbox'
    | '/notebook'
    | '/peers'
    | '/reports'
    | '/saved-reports'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/syndicate'
    | '/teacher'
    | '/timetable'
    | '/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/ai-analyser'
    | '/changelog'
    | '/criteria'
    | '/forecasting'
    | '/grades'
    | '/inbox'
    | '/notebook'
    | '/peers'
    | '/reports'
    | '/saved-reports'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/syndicate'
    | '/teacher'
    | '/timetable'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/advanced'
    | '/ai-analyser'
    | '/changelog'
    | '/criteria'
    | '/forecasting'
    | '/grades'
    | '/inbox'
    | '/notebook'
    | '/peers'
    | '/reports'
    | '/saved-reports'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/syndicate'
    | '/teacher'
    | '/timetable'
    | '/utilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRoute
  AiAnalyserRoute: typeof AiAnalyserRoute
  ChangelogRoute: typeof ChangelogRoute
  CriteriaRoute: typeof CriteriaRoute
  ForecastingRoute: typeof ForecastingRoute
  GradesRoute: typeof GradesRoute
  InboxRoute: typeof InboxRoute
  NotebookRoute: typeof NotebookRoute
  PeersRoute: typeof PeersRoute
  ReportsRoute: typeof ReportsRoute
  SavedReportsRoute: typeof SavedReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SyndicateRoute: typeof SyndicateRoute
  TeacherRoute: typeof TeacherRoute
  TimetableRoute: typeof TimetableRoute
  UtilitiesRoute: typeof UtilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate': {
      id: '/syndicate'
      path: '/syndicate'
      fullPath: '/syndicate'
      preLoaderRoute: typeof SyndicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-reports': {
      id: '/saved-reports'
      path: '/saved-reports'
      fullPath: '/saved-reports'
      preLoaderRoute: typeof SavedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criteria': {
      id: '/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof CriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analyser': {
      id: '/ai-analyser'
      path: '/ai-analyser'
      fullPath: '/ai-analyser'
      preLoaderRoute: typeof AiAnalyserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRoute,
  AiAnalyserRoute: AiAnalyserRoute,
  ChangelogRoute: ChangelogRoute,
  CriteriaRoute: CriteriaRoute,
  ForecastingRoute: ForecastingRoute,
  GradesRoute: GradesRoute,
  InboxRoute: InboxRoute,
  NotebookRoute: NotebookRoute,
  PeersRoute: PeersRoute,
  ReportsRoute: ReportsRoute,
  SavedReportsRoute: SavedReportsRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SyndicateRoute: SyndicateRoute,
  TeacherRoute: TeacherRoute,
  TimetableRoute: TimetableRoute,
  UtilitiesRoute: UtilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
